baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Stealth Systems Field Notes'
theme = 'PaperMod'

[params]
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
